### ISSUE TITLE
Client API not working

### ISSUE THREAD

**Issue by head-yote** [flathub/io.github.hydrusnetwork.hydrus#3]
Hi, not sure if this is where issues for the flatpak are to be posted.

When loading up my normal hydrus db, I immediately get an error in the bottom right of the window:

```
Could not start "client api"
```
```
v499, 2022/09/24 19:02:27: ModuleNotFoundError
No module named 'cryptography.hazmat.bindings._openssl'
Traceback (most recent call last):
  File "/app/hydrus/hydrus/client/ClientController.py", line 1787, in StartServices
    import twisted.internet.ssl
  File "/app/lib/python3.9/site-packages/twisted/internet/ssl.py", line 60, in <module>
    from OpenSSL import SSL
  File "/app/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/app/lib/python3.9/site-packages/OpenSSL/crypto.py", line 11, in <module>
    from OpenSSL._util import (
  File "/app/lib/python3.9/site-packages/OpenSSL/_util.py", line 5, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/app/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'
```

**Comment by bbhtt** [comment]
This was a packaging issue. Cryptography needs cffi to be built beforehand. Should be fixed with my PR. Please test.
